### ISSUE TITLE
link to more information broken

### ISSUE THREAD

**Issue by katska** [planningalerts-scrapers/marrickville#2]
Following a link from https://www.planningalerts.org.au/applications/1018611
to 
https://eproperty.marrickville.nsw.gov.au/eServices/P1/PublicNotices/PublicNoticeDetails.aspx?r=MC.P1.WEBGUEST&f=%24P1.ESB.PUBNOT.VIW&ApplicationId=DA201500082.02
returns an error - no information available. But searching for the DA from the council website returns the information wanted.

**Comment by LoveMyData** [comment]
Correct one is
https://eproperty.marrickville.nsw.gov.au/eServices/P1/eTrack/eTrackApplicationDetails.aspx?r=MC.P1.WEBGUEST&f=%24P1.ETR.APPDET.VIW&ApplicationId=DA201500082.02

Looks like a simple fix

Need to change from '/PublicNotices/PublicNoticeDetails.aspx?' to '/eTrack/eTrackApplicationDetails.aspx?' plus other bits.

**Comment by katska** [comment]
@LoveMyData great news!
